### ISSUE TITLE
Odroid XU4

### ISSUE THREAD

**Issue by esignoretti** [avujic/xmr_arch64#2]
Hi,
I'm new to Cryptomining and I'm still experimenting. 

I compiled the software on Odroid XU4 (Ubuntu). 
it starts but crashes in few seconds, after this message: [2018-01-14 20:13:47] new job from xmrpool.eu:3333 diff 10000

does it depend on the fact that RPi3 CPU has support for AES-NI while mine doesn't? 
thanks.

**Comment by avujic** [comment]
1) You can find in the section (Wiki->Performances) that Rpi3 actually did not implemented AES-NI.

2) Development platform for [xmr_arch64] is Arch Linux and Rpi3 platform. Windows support is abandoned but other Linux distributions support is inherited from [xmrig/xmrig]. 
Be advise to start testing with lower diff rates.
