### ISSUE TITLE
Performance improvements

### ISSUE THREAD

**Issue by josiahw** [avujic/xmr_arch64#4]
I managed to get this running a little faster using the following changes:
- add the following to the cmake flags: "-mcpu=cortex-a53 -march=armv8-a+crc -mtune=cortex-a53"
- enable hugepage support: "sudo sysctl -w vm.nr_hugepages=5"

With this, I get 8 H/s on 4 threads - all stock speeds, 64 bit debian, GCC 8.0.1.

**Comment by avujic** [comment]
@josiahw I can confirm that on my arch64 Rpi3 platform result is faster code. So, this suggestion is incorporated into project cmake flags. Thank you for contribution.
