### ISSUE TITLE
7.3 H/s instead of 16 H/s with 16 threads

### ISSUE THREAD

**Issue by rabota-alexey** [avujic/xmr_arch64#5]
I have Raspberry 3. I did all like in instructions for ruspberry pi 3 + AltLinux for raspberry 3 x64. But I could get only 7.3 H/s, though I have 16 threads in config file and system is clean and idle. In your "[CPU mining performance](https://github.com/avujic/xmr_arch64#cpu-mining-performance)" section you said it can be 16 H/s. Could you help me to figure out how can I reach 16 H/s? 

My config file:
[xmr_arch64_config.txt](https://github.com/avujic/xmr_arch64/files/1822000/xmr_arch64_config.txt)

**Comment by avujic** [comment]
@rabota-alexey 
Try to play with number of threads 8,16,24,32.
Please check out screen shot from my pool.
![screenshot from 2018-03-19 14-33-18](https://user-images.githubusercontent.com/23489117/37598662-225b711e-2b83-11e8-8bff-8e863c3bf8bd.png)

**Comment by avujic** [comment]
Hash printout should be improved for sure.

**Comment by rabota-alexey** [comment]
**Do you have large pages enabled?**
yes, I did it in this way:
sudo echo "vm.nr_hugepages=1024" >> /etc/sysctl.conf
and it shows me that HugePages_Total value from /proc/meminfo
What nr_hugepages size I should put?

**Try to play with number of threads 8,16,24,32.**
When I put 32, a speed always displays empty. Tomorrow will check other threads` amounts

**Please check out screen shot from my pool.**
how did u get it?

**Comment by avujic** [comment]
It is pool side screen shot [ https://supportxmr.com ]
