### ISSUE TITLE
No support for new PoW algorithm?

### ISSUE THREAD

**Issue by ordtrogen** [avujic/xmr_arch64#7]
Just looking at the dates for the last commits, it seems xmr_arch64 has not been updated for the soon-to-activate (in ~4 days) changes in PoW algorithm.

Any plans?

**Comment by avujic** [comment]
We will catch this PoW change in next 2-3 weeks.

**Comment by avujic** [comment]
Done.

**Comment by ordtrogen** [comment]
Seems to be working. Thanks!
Great to have RPi support during these (short?) days of lowered hash rate  :-)

**Comment by avujic** [comment]
Yes ;-)
