### ISSUE TITLE
Build error after last update

### ISSUE THREAD

**Issue by ordtrogen** [avujic/xmr_arch64#9]
first pic shows result of %git pull

![image](https://user-images.githubusercontent.com/15184875/38794920-eff2e1dc-4156-11e8-83e2-4d40cbc79ca2.png)

Here's the build error:

![image](https://user-images.githubusercontent.com/15184875/38794959-112bd11a-4157-11e8-9f6d-32d811c22563.png)

**Comment by avujic** [comment]
Can I ask you to perfom 'git clone' again, if error persists please let me know.

**Comment by avujic** [comment]
Will be resolved ASAP.

**Comment by avujic** [comment]
Now should work, please confirm.

**Comment by avujic** [comment]
Very good.
